# -*- coding: utf-8 -*-
"""20230427 백주원.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/165zN2etomMCNTt61qSgPSbWA0rg_dVdC
"""

import pandas as pd
import numpy as np
pass

import pandas as pd
import numpy as np

student_data = [['홍길동', 80,70,80],
                ['박철수', 60,70,80],
                ['김영희', 70,90,80]]
df=pd.Series(student_data)

print(df)

import pandas as pd
import numpy as np

student_data = [['홍길동', 80, 70, 80],
                ['박철수', 60, 70, 80],
                ['김영희', 70, 90, 80]]

# 컬럼 이름을 리스트로 지정
column_names = ['이름', '국어', '영어', '수학']

# 데이터프레임 생성
df = pd.DataFrame(student_data, columns=column_names)

# 데이터프레임 출력
df

korean_scores = df['국어']
korean_scores

import pandas as pd
import numpy as np

student_data = [['홍길동', 80, 70, 80],
                ['박철수', 60, 70, 80],
                ['김영희', 70, 90, 80]]

# 컬럼 이름을 리스트로 지정
column_names = ['이름', '국어', '영어', '수학']

# 데이터프레임 생성
df = pd.DataFrame(student_data, columns=column_names)

# 데이터프레임 출력
df

korean_scores = df['국어']
korean_scores

import pandas as pd
import numpy as np

student_data = [['홍길동', 80, 70, 80],
                ['박철수', 60, 70, 80],
                ['김영희', 70, 90, 80]]

# 컬럼 이름을 리스트로 지정
column_names = ['이름', '국어', '영어', '수학']

# 데이터프레임 생성
df = pd.DataFrame(student_data, columns=column_names)

# 데이터프레임 출력
df

df2 = df.iloc[0]
df2

import pandas as pd

student_data = [['홍길동', 80, 70, 80],
                ['박철수', 60, 70, 80],
                ['김영희', 70, 90, 80]]

# 컬럼 이름을 리스트로 지정
column_names = ['이름', '국어', '영어', '수학']

# 데이터프레임 생성
df = pd.DataFrame(student_data, columns=column_names)

# '사회' 칼럼 추가
df['사회'] = [50, 60, 70]

# 데이터프레임 출력
df

# '사회' 칼럼 삭제
df = df.drop('사회', axis=1)

# 데이터프레임 출력
df

# '박철수' 행 출력
rest = df.loc[df['이름'] == '박철수']
rest

# '박철수' 행의 인덱스를 찾아서 영어 점수 업데이트
row_index = df[df['이름'] == '박철수'].index[0]
df.loc[row_index, '영어'] = 100

# 변경된 데이터프레임 출력
df

# '국어' 점수가 70 이상인 데이터 추출
kor = df[df['국어'] >= 70]

# 추출된 데이터프레임 출력
kor

# '국어' 점수가 70이고 '수학' 점수가 80을 초과하는 데이터 추출
da1 = df[(df['국어'] == 70) & (df['수학'] >= 80)]

# 추출된 데이터프레임 출력
da1

# '국어' 점수가 80 이상이거나 '영어' 점수가 80 이상인 데이터 추출
da2 = df[(df['국어'] >= 80) | (df['영어'] >= 80)]

# 추출된 데이터프레임 출력
da2

# '이름' 컬럼을 행 인덱스로 설정
df = df.set_index('이름')

# 변경된 데이터프레임 출력
df

# '홍길동'의 국어 점수 조회
hgc = df.loc['홍길동', '국어']
hgc

# 열 방향으로 합계를 계산
sum_s = df.sum(axis=0)

# 합계 출력
sum_s

# 행 방향으로 합계를 계산
sum_1 = df.sum(axis=1)

# 합계 출력
sum_1

import pandas as pd

student_data = [['홍길동', 80, 70, 80],
                ['박철수', 60, 70, 80],
                ['김영희', 70, 90, 80]]

# 컬럼 이름을 리스트로 지정
column_names = ['이름', '국어', '영어', '수학']

# 데이터프레임 생성
df = pd.DataFrame(student_data, columns=column_names)

# 데이터프레임 출력
print(df)

# 행 방향으로 합계를 계산하여 "합계"라는 새로운 컬럼 추가
df['합계'] = df.sum(axis=1)

# 변경된 데이터프레임 출력
df

df

# 3번째 인덱스에 '백주원'의 성적 추가
df.loc[3] = ['백주원', 100, 100, 100, None]

# 변경된 데이터프레임 출력
df

# 결측값 확인
values = df.isna()

# 변경된 데이터프레임 출력
values

# 결측값 개수 확인
count = df.isna().sum()

# 결측값 개수 출력
count

# '합계' 칼럼의 이름을 '총점'으로 변경
df = df.rename(columns={'합계': '총점'})

# 변경된 데이터프레임 출력
df

# 본인 이름의 행 선택
my_name = '백주원'
my_row = df[df['이름'] == my_name]

# 합계 계산
my_total = my_row[['국어', '영어', '수학']].sum().sum()

# 총점 업데이트
df.loc[df['이름'] == my_name, '총점'] = my_total

# 변경된 데이터프레임 출력
df